#!/bin/bash



#Install framework dependencies:
apt-get install yara python-yara python-progressbar
pip install interruptingcow

#Install network client and server dependencies:
apt-get install libzmq3 python-zmq python-gevent python-pexpect

#Install module dependencies:
apt-get install python-ipy python-m2crypto python-pefile python-pyclamd liblzma5 libimage-exiftool-perl python-msgpack libfuzzy-dev python-cffi python-dev unrar
pip install fluent-logger olefile ssdeep py-unrar2 pylzma
wget https://github.com/smarnach/pyexiftool/archive/master.zip
unzip master.zip
cd pyexiftool-master
python setup.py build
python setup.py install

