# Copyright 2020 National Technology & Engineering Solutions of Sandia, LLC 
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S. 
# Government retains certain rights in this software.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import yara

# Import classes and helpers from the Laika framework
from laikaboss.util import get_option
from laikaboss.si_module import SI_MODULE

class META_RTF_CONTROLWORDS(SI_MODULE):
    ''' 
    counts classes of control words from RTF files
    '''

    def __init__(self):
        self.module_name = "META_RTF_CONTROLWORDS"
        self.rules = None
        
    def _run(self, scanObject, result, depth, args):
        
        #lazy compile rules, not using yara_on_demand due to signatures in string vs. file
        if not self.rules:
            self.rules = yara.compile(source=rtf_rules_source)
                
        matches = self.rules.match(data=scanObject.buffer)
        for match in matches:
            scanObject.addMetadata(self.module_name, match.rule[4:], len(match.strings))

        return []


rtf_rules_source = r"""

rule rtf_position_tabs
{
    strings:
        $pindtabqc = "\\pindtabqc"
        $pindtabql = "\\pindtabql"
        $pindtabqr = "\\pindtabqr"
        $pmartabqc = "\\pmartabqc"
        $pmartabql = "\\pmartabql"
        $pmartabqr = "\\pmartabqr"
        $ptabldot = "\\ptabldot"
        $ptablmdot = "\\ptablmdot"
        $ptablminus = "\\ptablminus"
        $ptablnone = "\\ptablnone"
        $ptabluscore = "\\ptabluscore"
    condition:
        any of them
}
rule rtf_character_properties
{
    strings:
        $ab = "\\ab"
        $acaps = "\\acaps"
        $acf = "\\acf"
        $adn = "\\adn"
        $aexpnd = "\\aexpnd"
        $af = "\\af"
        $afs = "\\afs"
        $ai = "\\ai"
        $alang = "\\alang"
        $aoutl = "\\aoutl"
        $ascaps = "\\ascaps"
        $ashad = "\\ashad"
        $astrike = "\\astrike"
        $aul = "\\aul"
        $auld = "\\auld"
        $auldb = "\\auldb"
        $aulnone = "\\aulnone"
        $aulw = "\\aulw"
        $aup = "\\aup"
        $dbch = "\\dbch"
        $fcs = "\\fcs"
        $hich = "\\hich"
        $loch = "\\loch"
    condition:
        any of them
}
rule rtf_bookmarks
{
    strings:
        $bkmkcolf = "\\bkmkcolf"
        $bkmkcoll = "\\bkmkcoll"
        $bkmkend = "\\bkmkend"
        $bkmkstart = "\\bkmkstart"
        $mvfmf = "\\mvfmf"
        $mvfml = "\\mvfml"
        $mvtof = "\\mvtof"
        $mvtol = "\\mvtol"

    condition:
        any of them
}
rule rtf_bullets
{
    strings:
        $ilvl = "\\ilvl"
        $listtext = "\\listtext"
        $pn = "\\pn"
        $pnacross = "\\pnacross"
        $pnaiu = "\\pnaiu"
        $pnaiud = "\\pnaiud"
        $pnaiueo = "\\pnaiueo"
        $pnaiueod = "\\pnaiueod"
        $pnb = "\\pnb"
        $pnbidia = "\\pnbidia"
        $pnbidib = "\\pnbidib"
        $pncaps = "\\pncaps"
        $pncard = "\\pncard"
        $pncf = "\\pncf"
        $pnchosung = "\\pnchosung"
        $pncnum = "\\pncnum"
        $pndbnum = "\\pndbnum"
        $pndbnumd = "\\pndbnumd"
        $pndbnumk = "\\pndbnumk"
        $pndbnuml = "\\pndbnuml"
        $pndbnumt = "\\pndbnumt"
        $pndec = "\\pndec"
        $pndecd = "\\pndecd"
        $pnf = "\\pnf"
        $pnfs = "\\pnfs"
        $pnganada = "\\pnganada"
        $pngbnum = "\\pngbnum"
        $pngbnumd = "\\pngbnumd"
        $pngbnumk = "\\pngbnumk"
        $pngbnuml = "\\pngbnuml"
        $pnhang = "\\pnhang"
        $pni = "\\pni"
        $pnindent = "\\pnindent"
        $pniroha = "\\pniroha"
        $pnirohad = "\\pnirohad"
        $pnlcltr = "\\pnlcltr"
        $pnlcrm = "\\pnlcrm"
        $pnlvl = "\\pnlvl"
        $pnlvlblt = "\\pnlvlblt"
        $pnlvlbody = "\\pnlvlbody"
        $pnlvlcont = "\\pnlvlcont"
        $pnnumonce = "\\pnnumonce"
        $pnord = "\\pnord"
        $pnordt = "\\pnordt"
        $pnprev = "\\pnprev"
        $pnqc = "\\pnqc"
        $pnql = "\\pnql"
        $pnqr = "\\pnqr"
        $pnrestart = "\\pnrestart"
        $pnscaps = "\\pnscaps"
        $pnsp = "\\pnsp"
        $pnstart = "\\pnstart"
        $pnstrike = "\\pnstrike"
        $pntext = "\\pntext"
        $pntxta = "\\pntxta"
        $pntxtb = "\\pntxtb"
        $pnucltr = "\\pnucltr"
        $pnucrm = "\\pnucrm"
        $pnul = "\\pnul"
        $pnuld = "\\pnuld"
        $pnuldash = "\\pnuldash"
        $pnuldashd = "\\pnuldashd"
        $pnuldashdd = "\\pnuldashdd"
        $pnuldb = "\\pnuldb"
        $pnulhair = "\\pnulhair"
        $pnulnone = "\\pnulnone"
        $pnulth = "\\pnulth"
        $pnulw = "\\pnulw"
        $pnulwave = "\\pnulwave"
        $pnzodiac = "\\pnzodiac"
        $pnzodiacd = "\\pnzodiacd"
        $pnzodiacl = "\\pnzodiacl"
   condition:
        any of them
}
rule rtf_characters
{
    strings:
        $chbgbdiag = "\\chbgbdiag"
        $chbgcross = "\\chbgcross"
        $chbgdcross = "\\chbgdcross"
        $chbgdkbdiag = "\\chbgdkbdiag"
        $chbgdkcross = "\\chbgdkcross"
        $chbgdkdcross = "\\chbgdkdcross"
        $chbgdkfdiag = "\\chbgdkfdiag"
        $chbgdkhoriz = "\\chbgdkhoriz"
        $chbgdkvert = "\\chbgdkvert"
        $chbgfdiag = "\\chbgfdiag"
        $chbghoriz = "\\chbghoriz"
        $chbgvert = "\\chbgvert"
        $chbrdr = "\\chbrdr"
        $chcbpat = "\\chcbpat"
        $chcfpat = "\\chcfpat"
        $chshdng = "\\chshdng"
        $crauth = "\\crauth"
        $crdate = "\\crdate"
        $deleted = "\\deleted"
        $mvauth = "\\mvauth"
        $mvdate = "\\mvdate"
        $mvf = "\\mvf"
        $mvt = "\\mvt"
        $revauth = "\\revauth"
        $revauthdel = "\\revauthdel"
        $revdttm = "\\revdttm"
        $revdttmdel = "\\revdttmdel"
        $revised = "\\revised"
        $ansi = "\\ansi"
        $ansicpg = "\\ansicpg"
        $fbidis = "\\fbidis"
        $mac = "\\mac"
        $pc = "\\pc"
        $pca = "\\pca"
        $impr = "\\impr"
        $striked1 = "\\striked1"
   condition:
        any of them
}
rule rtf_codepage
{
    strings:
        $cpg = "\\cpg"
   condition:
        any of them
}
rule rtf_color
{
    strings:
        $colorschememapping = "\\colorschememapping"
        $blue = "\\blue"
        $caccentfive = "\\caccentfive"
        $caccentfour = "\\caccentfour"
        $caccentone = "\\caccentone"
        $caccentsix = "\\caccentsix"
        $caccentthree = "\\caccentthree"
        $caccenttwo = "\\caccenttwo"
        $cbackgroundone = "\\cbackgroundone"
        $cbackgroundtwo = "\\cbackgroundtwo"
        $cfollowedhyperlink = "\\cfollowedhyperlink"
        $chyperlink = "\\chyperlink"
        $cmaindarkone = "\\cmaindarkone"
        $cmaindarktwo = "\\cmaindarktwo"
        $cmainlightone = "\\cmainlightone"
        $cmainlighttwo = "\\cmainlighttwo"
        $colortbl = "\\colortbl"
        $cshade = "\\cshade"
        $ctextone = "\\ctextone"
        $ctexttwo = "\\ctexttwo"
        $ctint = "\\ctint"
        $green = "\\green"
        $red = "\\red"
   condition:
        any of them
}
rule rtf_comments
{
    strings:
        $annotation = "\\annotation"
        $atnauthor = "\\atnauthor"
        $atndate = "\\atndate"
        $atnicn = "\\atnicn"
        $atnid = "\\atnid"
        $atnparent = "\\atnparent"
        $atnref = "\\atnref"
        $atntime = "\\atntime"
        $atrfend = "\\atrfend"
        $atrfstart = "\\atrfstart"
   condition:
        any of them
}
rule rtf_control_other
{
    strings:
        $disabled = "\\disabled"
        $htmlbase = "\\htmlbase"
        $htmlrtf = "\\htmlrtf"
        $htmltag = "\\htmltag"
        $mhtmltag = "\\mhtmltag"
        $protect = "\\protect"
        $pwd = "\\pwd"
        $urtf = "\\urtf"
   condition:
        any of them
}
rule rtf_datastore
{
    strings:
        $datastore = "\\datastore"
   condition:
        any of them
}
rule rtf_xml
{
    strings:
        $xmlattr = "\\xmlattr"
        $xmlattrname = "\\xmlattrname"
        $xmlattrns = "\\xmlattrns"
        $xmlattrvalue = "\\xmlattrvalue"
        $xmlclose = "\\xmlclose"
        $xmlname = "\\xmlname"
        $xmlnstbl = "\\xmlnstbl"
        $xmlopen = "\\xmlopen"
        $xmlsdttcell = "\\xmlsdttcell"
        $xmlsdttpara = "\\xmlsdttpara"
        $xmlsdttregular = "\\xmlsdttregular"
        $xmlsdttrow = "\\xmlsdttrow"
        $xmlsdttunknown = "\\xmlsdttunknown"
        $xmlns = "\\xmlns"
   condition:
        any of them
}
rule rtf_defaults
{
    strings:
        $adeff = "\\adeff"
        $adeflang = "\\adeflang"
        $deff = "\\deff"
        $deflang = "\\deflang"
        $deflangfe = "\\deflangfe"
        $stshfbi = "\\stshfbi"
        $stshfdbch = "\\stshfdbch"
        $stshfhich = "\\stshfhich"
        $stshfloch = "\\stshfloch"
        $defchp = "\\defchp"
        $defpap = "\\defpap"
   condition:
        any of them
}
rule rtf_formatting
{
    strings:
        $aenddoc = "\\aenddoc"
        $aendnotes = "\\aendnotes"
        $afelev = "\\afelev"
        $aftnbj = "\\aftnbj"
        $aftncn = "\\aftncn"
        $aftnnalc = "\\aftnnalc"
        $aftnnar = "\\aftnnar"
        $aftnnauc = "\\aftnnauc"
        $aftnnchi = "\\aftnnchi"
        $aftnnchosung = "\\aftnnchosung"
        $aftnncnum = "\\aftnncnum"
        $aftnndbar = "\\aftnndbar"
        $aftnndbnum = "\\aftnndbnum"
        $aftnndbnumd = "\\aftnndbnumd"
        $aftnndbnumk = "\\aftnndbnumk"
        $aftnndbnumt = "\\aftnndbnumt"
        $aftnnganada = "\\aftnnganada"
        $aftnngbnum = "\\aftnngbnum"
        $aftnngbnumd = "\\aftnngbnumd"
        $aftnngbnumk = "\\aftnngbnumk"
        $aftnngbnuml = "\\aftnngbnuml"
        $aftnnrlc = "\\aftnnrlc"
        $aftnnruc = "\\aftnnruc"
        $aftnnzodiac = "\\aftnnzodiac"
        $aftnnzodiacd = "\\aftnnzodiacd"
        $aftnnzodiacl = "\\aftnnzodiacl"
        $aftnrestart = "\\aftnrestart"
        $aftnrstcont = "\\aftnrstcont"
        $aftnsep = "\\aftnsep"
        $aftnsepc = "\\aftnsepc"
        $aftnstart = "\\aftnstart"
        $aftntj = "\\aftntj"
        $allowfieldendsel = "\\allowfieldendsel"
        $allprot = "\\allprot"
        $alntblind = "\\alntblind"
        $annotprot = "\\annotprot"
        $ApplyBrkRules = "\\ApplyBrkRules"
        $asianbrkrule = "\\asianbrkrule"
        $autofmtoverride = "\\autofmtoverride"
        $background = "\\background"
        $bdbfhdr = "\\bdbfhdr"
        $bdrrlswsix = "\\bdrrlswsix"
        $bookfold = "\\bookfold"
        $bookfoldrev = "\\bookfoldrev"
        $bookfoldsheets = "\\bookfoldsheets"
        $brdrart = "\\brdrart"
        $brkfrm = "\\brkfrm"
        $cachedcolbal = "\\cachedcolbal"
        $cts = "\\cts"
        $cvmme = "\\cvmme"
        $defformat = "\\defformat"
        $deftab = "\\deftab"
        $dghorigin = "\\dghorigin"
        $dghshow = "\\dghshow"
        $dghspace = "\\dghspace"
        $dgmargin = "\\dgmargin"
        $dgsnap = "\\dgsnap"
        $dgvorigin = "\\dgvorigin"
        $dgvshow = "\\dgvshow"
        $dgvspace = "\\dgvspace"
        $dntblnsbdb = "\\dntblnsbdb"
        $doctemp = "\\doctemp"
        $doctype = "\\doctype"
        $donotembedlingdata = "\\donotembedlingdata"
        $donotembedsysfont = "\\donotembedsysfont"
        $donotshowcomments = "\\donotshowcomments"
        $donotshowinsdel = "\\donotshowinsdel"
        $donotshowmarkup = "\\donotshowmarkup"
        $donotshowprops = "\\donotshowprops"
        $enddoc = "\\enddoc"
        $endnotes = "\\endnotes"
        $enforceprot = "\\enforceprot"
        $expshrtn = "\\expshrtn"
        $facingp = "\\facingp"
        $fchars = "\\fchars"
        $felnbrelev = "\\felnbrelev"
        $fet = "\\fet"
        $forceupgrade = "\\forceupgrade"
        $formdisp = "\\formdisp"
        $formprot = "\\formprot"
        $formshade = "\\formshade"
        $fracwidth = "\\fracwidth"
        $fromhtml = "\\fromhtml"
        $fromtext = "\\fromtext"
        $ftnalt = "\\ftnalt"
        $ftnbj = "\\ftnbj"
        $ftncn = "\\ftncn"
        $ftnlytwnine = "\\ftnlytwnine"
        $ftnnalc = "\\ftnnalc"
        $ftnnar = "\\ftnnar"
        $ftnnauc = "\\ftnnauc"
        $ftnnchi = "\\ftnnchi"
        $ftnnchosung = "\\ftnnchosung"
        $ftnncnum = "\\ftnncnum"
        $ftnndbar = "\\ftnndbar"
        $ftnndbnum = "\\ftnndbnum"
        $ftnndbnumd = "\\ftnndbnumd"
        $ftnndbnumk = "\\ftnndbnumk"
        $ftnndbnumt = "\\ftnndbnumt"
        $ftnnganada = "\\ftnnganada"
        $ftnngbnum = "\\ftnngbnum"
        $ftnngbnumd = "\\ftnngbnumd"
        $ftnngbnumk = "\\ftnngbnumk"
        $ftnngbnuml = "\\ftnngbnuml"
        $ftnnrlc = "\\ftnnrlc"
        $ftnnruc = "\\ftnnruc"
        $ftnnzodiac = "\\ftnnzodiac"
        $ftnnzodiacd = "\\ftnnzodiacd"
        $ftnnzodiacl = "\\ftnnzodiacl"
        $ftnrestart = "\\ftnrestart"
        $ftnrstcont = "\\ftnrstcont"
        $ftnrstpg = "\\ftnrstpg"
        $ftnsep = "\\ftnsep"
        $ftnsepc = "\\ftnsepc"
        $ftnstart = "\\ftnstart"
        $ftntj = "\\ftntj"
        $grfdocevents = "\\grfdocevents"
        $gutter = "\\gutter"
        $gutterprl = "\\gutterprl"
        $horzdoc = "\\horzdoc"
        $htmautsp = "\\htmautsp"
        $hwelev2007 = "\\hwelev2007"
        $hyphauto = "\\hyphauto"
        $hyphcaps = "\\hyphcaps"
        $hyphconsec = "\\hyphconsec"
        $hyphhotz = "\\hyphhotz"
        $ignoremixedcontent = "\\ignoremixedcontent"
        $ilfomacatclnup = "\\ilfomacatclnup"
        $indrlsweleven = "\\indrlsweleven"
        $jcompress = "\\jcompress"
        $jexpand = "\\jexpand"
        $jsksu = "\\jsksu"
        $krnprsnet = "\\krnprsnet"
        $ksulang = "\\ksulang"
        $landscape = "\\landscape"
        $lchars = "\\lchars"
        $linestart = "\\linestart"
        $linkstyles = "\\linkstyles"
        $lnbrkrule = "\\lnbrkrule"
        $lnongrid = "\\lnongrid"
        $ltrdoc = "\\ltrdoc"
        $lytcalctblwd = "\\lytcalctblwd"
        $lytexcttp = "\\lytexcttp"
        $lytprtmet = "\\lytprtmet"
        $lyttblrtgr = "\\lyttblrtgr"
        $makebackup = "\\makebackup"
        $margb = "\\margb"
        $margl = "\\margl"
        $margmirror = "\\margmirror"
        $margr = "\\margr"
        $margt = "\\margt"
        $msmcap = "\\msmcap"
        $muser = "\\muser"
        $newtblstyruls = "\\newtblstyruls"
        $nextfile = "\\nextfile"
        $noafcnsttbl = "\\noafcnsttbl"
        $nobrkwrptbl = "\\nobrkwrptbl"
        $nocolbal = "\\nocolbal"
        $nocompatoptions = "\\nocompatoptions"
        $nocxsptable = "\\nocxsptable"
        $noextrasprl = "\\noextrasprl"
        $nofeaturethrottle = "\\nofeaturethrottle"
        $nogrowautofit = "\\nogrowautofit"
        $noindnmbrts = "\\noindnmbrts"
        $nojkernpunct = "\\nojkernpunct"
        $nolead = "\\nolead"
        $nolnhtadjtbl = "\\nolnhtadjtbl"
        $nospaceforul = "\\nospaceforul"
        $notabind = "\\notabind"
        $notbrkcnstfrctbl = "\\notbrkcnstfrctbl"
        $notcvasp = "\\notcvasp"
        $notvatxbx = "\\notvatxbx"
        $nouicompat = "\\nouicompat"
        $noultrlspc = "\\noultrlspc"
        $noxlattoyen = "\\noxlattoyen"
        $ogutter = "\\ogutter"
        $oldas = "\\oldas"
        $oldlinewrap = "\\oldlinewrap"
        $otblrul = "\\otblrul"
        $paperh = "\\paperh"
        $paperw = "\\paperw"
        $pgbrdrb = "\\pgbrdrb"
        $pgbrdrfoot = "\\pgbrdrfoot"
        $pgbrdrhead = "\\pgbrdrhead"
        $pgbrdrl = "\\pgbrdrl"
        $pgbrdropt = "\\pgbrdropt"
        $pgbrdrr = "\\pgbrdrr"
        $pgbrdrsnap = "\\pgbrdrsnap"
        $pgbrdrt = "\\pgbrdrt"
        $pgnstart = "\\pgnstart"
        $prcolbl = "\\prcolbl"
        $printdata = "\\printdata"
        $private = "\\private"
        $protlevel = "\\protlevel"
        $psover = "\\psover"
        $psz = "\\psz"
        $readonlyrecommended = "\\readonlyrecommended"
        $readprot = "\\readprot"
        $relyonvml = "\\relyonvml"
        $remdttm = "\\remdttm"
        $rempersonalinfo = "\\rempersonalinfo"
        $revbar = "\\revbar"
        $revisions = "\\revisions"
        $revprop = "\\revprop"
        $revprot = "\\revprot"
        $rtldoc = "\\rtldoc"
        $rtlgutter = "\\rtlgutter"
        $saveinvalidxml = "\\saveinvalidxml"
        $saveprevpict = "\\saveprevpict"
        $showplaceholdtext = "\\showplaceholdtext"
        $showxmlerrors = "\\showxmlerrors"
        $snaptogridincell = "\\snaptogridincell"
        $spltpgpar = "\\spltpgpar"
        $splytwnine = "\\splytwnine"
        $sprsbsp = "\\sprsbsp"
        $sprslnsp = "\\sprslnsp"
        $sprsspbf = "\\sprsspbf"
        $sprstsm = "\\sprstsm"
        $sprstsp = "\\sprstsp"
        $stylelock = "\\stylelock"
        $stylelockbackcomp = "\\stylelockbackcomp"
        $stylelockenforced = "\\stylelockenforced"
        $stylelockqfset = "\\stylelockqfset"
        $stylelocktheme = "\\stylelocktheme"
        $stylesortmethod = "\\stylesortmethod"
        $subfontbysize = "\\subfontbysize"
        $swpbdr = "\\swpbdr"
        $template = "\\template"
        $themelang = "\\themelang"
        $themelangcs = "\\themelangcs"
        $themelangfe = "\\themelangfe"
        $toplinepunct = "\\toplinepunct"
        $trackformatting = "\\trackformatting"
        $trackmoves = "\\trackmoves"
        $transmf = "\\transmf"
        $truncatefontheight = "\\truncatefontheight"
        $truncex = "\\truncex"
        $tsd = "\\tsd"
        $twoonone = "\\twoonone"
        $useltbaln = "\\useltbaln"
        $usenormstyforlist = "\\usenormstyforlist"
        $usexform = "\\usexform"
        $utinl = "\\utinl"
        $validatexml = "\\validatexml"
        $vertdoc = "\\vertdoc"
        $viewbksp = "\\viewbksp"
        $viewkind = "\\viewkind"
        $viewnobound = "\\viewnobound"
        $viewscale = "\\viewscale"
        $viewzk = "\\viewzk"
        $wgrffmtfilter = "\\wgrffmtfilter"
        $widowctrl = "\\widowctrl"
        $windowcaption = "\\windowcaption"
        $wpjst = "\\wpjst"
        $wpsp = "\\wpsp"
        $wraptrsp = "\\wraptrsp"
        $writereservation = "\\writereservation"
        $writereservhash = "\\writereservhash"
        $wrppunct = "\\wrppunct"
        $xform = "\\xform"
   condition:
        any of them
}
rule rtf_docvar
{
    strings:
        $docvar = "\\docvar"
   condition:
        any of them
}
rule rtf_drawing
{
    strings:
        $hl = "\\hl"
        $hlfr = "\\hlfr"
        $hlloc = "\\hlloc"
        $hlsrc = "\\hlsrc"
        $hrule = "\\hrule"
        $hsv = "\\hsv"
        $do = "\\do"
        $dobxcolumn = "\\dobxcolumn"
        $dobxmargin = "\\dobxmargin"
        $dobxpage = "\\dobxpage"
        $dobymargin = "\\dobymargin"
        $dobypage = "\\dobypage"
        $dobypara = "\\dobypara"
        $dodhgt = "\\dodhgt"
        $dolock = "\\dolock"
        $dpaendhol = "\\dpaendhol"
        $dpaendl = "\\dpaendl"
        $dpaendsol = "\\dpaendsol"
        $dpaendw = "\\dpaendw"
        $dparc = "\\dparc"
        $dparcflipx = "\\dparcflipx"
        $dparcflipy = "\\dparcflipy"
        $dpastarthol = "\\dpastarthol"
        $dpastartl = "\\dpastartl"
        $dpastartsol = "\\dpastartsol"
        $dpastartw = "\\dpastartw"
        $dpcallout = "\\dpcallout"
        $dpcoa = "\\dpcoa"
        $dpcoaccent = "\\dpcoaccent"
        $dpcobestfit = "\\dpcobestfit"
        $dpcoborder = "\\dpcoborder"
        $dpcodabs = "\\dpcodabs"
        $dpcodbottom = "\\dpcodbottom"
        $dpcodcenter = "\\dpcodcenter"
        $dpcodescent = "\\dpcodescent"
        $dpcodtop = "\\dpcodtop"
        $dpcolength = "\\dpcolength"
        $dpcominusx = "\\dpcominusx"
        $dpcominusy = "\\dpcominusy"
        $dpcooffset = "\\dpcooffset"
        $dpcosmarta = "\\dpcosmarta"
        $dpcotdouble = "\\dpcotdouble"
        $dpcotright = "\\dpcotright"
        $dpcotsingle = "\\dpcotsingle"
        $dpcottriple = "\\dpcottriple"
        $dpcount = "\\dpcount"
        $dpellipse = "\\dpellipse"
        $dpendgroup = "\\dpendgroup"
        $dpfillbgcb = "\\dpfillbgcb"
        $dpfillbgcg = "\\dpfillbgcg"
        $dpfillbgcr = "\\dpfillbgcr"
        $dpfillbggray = "\\dpfillbggray"
        $dpfillbgpal = "\\dpfillbgpal"
        $dpfillfgcb = "\\dpfillfgcb"
        $dpfillfgcg = "\\dpfillfgcg"
        $dpfillfgcr = "\\dpfillfgcr"
        $dpfillfggray = "\\dpfillfggray"
        $dpfillfgpal = "\\dpfillfgpal"
        $dpfillpat = "\\dpfillpat"
        $dpgroup = "\\dpgroup"
        $dpline = "\\dpline"
        $dplinecob = "\\dplinecob"
        $dplinecog = "\\dplinecog"
        $dplinecor = "\\dplinecor"
        $dplinedado = "\\dplinedado"
        $dplinedadodo = "\\dplinedadodo"
        $dplinedash = "\\dplinedash"
        $dplinedot = "\\dplinedot"
        $dplinegray = "\\dplinegray"
        $dplinehollow = "\\dplinehollow"
        $dplinepal = "\\dplinepal"
        $dplinesolid = "\\dplinesolid"
        $dplinew = "\\dplinew"
        $dppolycount = "\\dppolycount"
        $dppolygon = "\\dppolygon"
        $dppolyline = "\\dppolyline"
        $dpptx = "\\dpptx"
        $dppty = "\\dppty"
        $dprect = "\\dprect"
        $dproundr = "\\dproundr"
        $dpshadow = "\\dpshadow"
        $dpshadx = "\\dpshadx"
        $dpshady = "\\dpshady"
        $dptxbtlr = "\\dptxbtlr"
        $dptxbx = "\\dptxbx"
        $dptxbxmar = "\\dptxbxmar"
        $dptxbxtext = "\\dptxbxtext"
        $dptxlrtb = "\\dptxlrtb"
        $dptxlrtbv = "\\dptxlrtbv"
        $dptxtbrl = "\\dptxtbrl"
        $dptxtbrlv = "\\dptxtbrlv"
        $dpx = "\\dpx"
        $dpxsize = "\\dpxsize"
        $dpy = "\\dpy"
        $dpysize = "\\dpysize"
   condition:
        any of them
}
rule rtf_asia
{
    strings:
        $cgrid = "\\cgrid"
        $g = "\\g"
        $gcw = "\\gcw"
        $gridtbl = "\\gridtbl"
        $nosectexpand = "\\nosectexpand"
        $ulhair = "\\ulhair"
        $horzvert = "\\horzvert"
        $twoinone = "\\twoinone"
   condition:
        any of them
}
rule rtf_fields
{
    strings:
        $datafield = "\\datafield"
        $date = "\\date"
        $field = "\\field"
        $fldalt = "\\fldalt"
        $flddirty = "\\flddirty"
        $fldedit = "\\fldedit"
        $fldinst = "\\fldinst"
        $fldlock = "\\fldlock"
        $fldpriv = "\\fldpriv"
        $fldrslt = "\\fldrslt"
        $fldtype = "\\fldtype"
        $time = "\\time"
        $wpeqn = "\\wpeqn"
   condition:
        any of them
}
rule rtf_files
{
    strings:
        $fid = "\\fid"
        $file = "\\file"
        $filetbl = "\\filetbl"
        $fnetwork = "\\fnetwork"
        $fnonfilesys = "\\fnonfilesys"
        $fosnum = "\\fosnum"
        $frelative = "\\frelative"
        $fvaliddos = "\\fvaliddos"
        $fvalidhpfs = "\\fvalidhpfs"
        $fvalidmac = "\\fvalidmac"
        $fvalidntfs = "\\fvalidntfs"
   condition:
        any of them
}
rule rtf_font
{
    strings:
        $acccircle = "\\acccircle"
        $acccomma = "\\acccomma"
        $accdot = "\\accdot"
        $accnone = "\\accnone"
        $accunderdot = "\\accunderdot"
        $animtext = "\\animtext"
        $b = "\\b"
        $caps = "\\caps"
        $cb = "\\cb"
        $cchs = "\\cchs"
        $cf = "\\cf"
        $charscalex = "\\charscalex"
        $cs = "\\cs"
        $dn = "\\dn"
        $embo = "\\embo"
        $expnd = "\\expnd"
        $expndtw = "\\expndtw"
        $f = "\\f"
        $fittext = "\\fittext"
        $fs = "\\fs"
        $i = "\\i"
        $kerning = "\\kerning"
        $lang = "\\lang"
        $langfe = "\\langfe"
        $langfenp = "\\langfenp"
        $langnp = "\\langnp"
        $ltrch = "\\ltrch"
        $noproof = "\\noproof"
        $nosupersub = "\\nosupersub"
        $outl = "\\outl"
        $plain = "\\plain"
        $rtlch = "\\rtlch"
        $scaps = "\\scaps"
        $shad = "\\shad"
        $strike = "\\strike"
        $sub = "\\sub"
        $super = "\\super"
        $ul = "\\ul"
        $ulc = "\\ulc"
        $uld = "\\uld"
        $uldash = "\\uldash"
        $uldashd = "\\uldashd"
        $uldashdd = "\\uldashdd"
        $uldb = "\\uldb"
        $ulhwave = "\\ulhwave"
        $ulldash = "\\ulldash"
        $ulnone = "\\ulnone"
        $ulth = "\\ulth"
        $ulthd = "\\ulthd"
        $ulthdash = "\\ulthdash"
        $ulthdashd = "\\ulthdashd"
        $ulthdashdd = "\\ulthdashdd"
        $ulthldash = "\\ulthldash"
        $ululdbwave = "\\ululdbwave"
        $ulw = "\\ulw"
        $ulwave = "\\ulwave"
        $up = "\\up"
        $v = "\\v"
        $webhidden = "\\webhidden"
        $fjgothic = "\\fjgothic"
        $fjminchou = "\\fjminchou"
        $jis = "\\jis"
        $falt = "\\falt"
        $fbias = "\\fbias"
        $fbidi = "\\fbidi"
        $fcharset = "\\fcharset"
        $fdecor = "\\fdecor"
        $fetch = "\\fetch"
        $fmodern = "\\fmodern"
        $fname = "\\fname"
        $fnil = "\\fnil"
        $fontemb = "\\fontemb"
        $fontfile = "\\fontfile"
        $fonttbl = "\\fonttbl"
        $fprq = "\\fprq"
        $froman = "\\froman"
        $fscript = "\\fscript"
        $fswiss = "\\fswiss"
        $ftech = "\\ftech"
        $ftnil = "\\ftnil"
        $fttruetype = "\\fttruetype"
        $panose = "\\panose"
   condition:
        any of them
}
rule rtf_footnote
{
    strings:
        $footnote = "\\footnote"
   condition:
        any of them
}
rule rtf_form
{
    strings:
        $ffdefres = "\\ffdefres"
        $ffdeftext = "\\ffdeftext"
        $ffentrymcr = "\\ffentrymcr"
        $ffexitmcr = "\\ffexitmcr"
        $ffformat = "\\ffformat"
        $ffhaslistbox = "\\ffhaslistbox"
        $ffhelptext = "\\ffhelptext"
        $ffhps = "\\ffhps"
        $ffl = "\\ffl"
        $ffmaxlen = "\\ffmaxlen"
        $ffname = "\\ffname"
        $ffownhelp = "\\ffownhelp"
        $ffownstat = "\\ffownstat"
        $ffprot = "\\ffprot"
        $ffrecalc = "\\ffrecalc"
        $ffres = "\\ffres"
        $ffsize = "\\ffsize"
        $ffstattext = "\\ffstattext"
        $fftype = "\\fftype"
        $fftypetxt = "\\fftypetxt"
        $formfield = "\\formfield"
   condition:
        any of them
}
rule rtf_generator
{
    strings:
        $generator = "\\generator"
   condition:
        any of them
}
rule rtf_headers
{
    strings:
        $footer = "\\footer"
        $footerf = "\\footerf"
        $footerl = "\\footerl"
        $footerr = "\\footerr"
        $header = "\\header"
        $headerf = "\\headerf"
        $headerl = "\\headerl"
        $headerr = "\\headerr"
   condition:
        any of them
}
rule rtf_highlight
{
    strings:
        $highlight = "\\highlight"
   condition:
        any of them
}
rule rtf_hyphen
{
    strings:
        $chhres = "\\chhres"
        $hres = "\\hres"
   condition:
        any of them
}
rule rtf_index
{
    strings:
        $bxe = "\\bxe"
        $ixe = "\\ixe"
        $pxe = "\\pxe"
        $rxe = "\\rxe"
        $txe = "\\txe"
        $xe = "\\xe"
        $xef = "\\xef"
        $yxe = "\\yxe"
   condition:
        any of them
}
rule rtf_info
{
    strings:
        $author = "\\author"
        $buptim = "\\buptim"
        $category = "\\category"
        $comment = "\\comment"
        $company = "\\company"
        $creatim = "\\creatim"
        $doccomm = "\\doccomm"
        $dy = "\\dy"
        $edmins = "\\edmins"
        $hlinkbase = "\\hlinkbase"
        $hr = "\\hr"
        $id = "\\id"
        $info = "\\info"
        $keywords = "\\keywords"
        $linkval = "\\linkval"
        $manager = "\\manager"
        $min = "\\min"
        $mo = "\\mo"
        $nofchars = "\\nofchars"
        $nofcharsws = "\\nofcharsws"
        $nofpages = "\\nofpages"
        $nofwords = "\\nofwords"
        $operator = "\\operator"
        $printim = "\\printim"
        $propname = "\\propname"
        $proptype = "\\proptype"
        $revtim = "\\revtim"
        $sec = "\\sec"
        $staticval = "\\staticval"
        $subject = "\\subject"
        $title = "\\title"
        $userprops = "\\userprops"
        $vern = "\\vern"
        $version = "\\version"
        $yr = "\\yr"
   condition:
        any of them
}
rule rtf_list
{
    strings:
        $lvltentative = "\\lvltentative"
        $jclisttab = "\\jclisttab"
        $levelfollow = "\\levelfollow"
        $levelindent = "\\levelindent"
        $leveljc = "\\leveljc"
        $leveljcn = "\\leveljcn"
        $levellegal = "\\levellegal"
        $levelnfc = "\\levelnfc"
        $levelnfcn = "\\levelnfcn"
        $levelnorestart = "\\levelnorestart"
        $levelnumbers = "\\levelnumbers"
        $levelold = "\\levelold"
        $levelpicture = "\\levelpicture"
        $levelpicturenosize = "\\levelpicturenosize"
        $levelprev = "\\levelprev"
        $levelprevspace = "\\levelprevspace"
        $levelspace = "\\levelspace"
        $levelstartat = "\\levelstartat"
        $leveltemplateid = "\\leveltemplateid"
        $leveltext = "\\leveltext"
        $lfolevel = "\\lfolevel"
        $list = "\\list"
        $listhybrid = "\\listhybrid"
        $listid = "\\listid"
        $listlevel = "\\listlevel"
        $listname = "\\listname"
        $listoverride = "\\listoverride"
        $listoverridecount = "\\listoverridecount"
        $listoverrideformat = "\\listoverrideformat"
        $listoverridestartat = "\\listoverridestartat"
        $listoverridetable = "\\listoverridetable"
        $listpicture = "\\listpicture"
        $listrestarthdn = "\\listrestarthdn"
        $listsimple = "\\listsimple"
        $liststyleid = "\\liststyleid"
        $liststylename = "\\liststylename"
        $listtable = "\\listtable"
        $listtemplateid = "\\listtemplateid"
        $ls = "\\ls"
   condition:
        any of them
}
rule rtf_mac
{
    strings:
        $bkmkpub = "\\bkmkpub"
        $pubauto = "\\pubauto"
   condition:
        any of them
}
rule rtf_mail
{
    strings:
        $mailmerge = "\\mailmerge"
        $mmaddfieldname = "\\mmaddfieldname"
        $mmattach = "\\mmattach"
        $mmblanklines = "\\mmblanklines"
        $mmconnectstr = "\\mmconnectstr"
        $mmconnectstrdata = "\\mmconnectstrdata"
        $mmdatasource = "\\mmdatasource"
        $mmdatatypeaccess = "\\mmdatatypeaccess"
        $mmdatatypeexcel = "\\mmdatatypeexcel"
        $mmdatatypefile = "\\mmdatatypefile"
        $mmdatatypeodbc = "\\mmdatatypeodbc"
        $mmdatatypeodso = "\\mmdatatypeodso"
        $mmdatatypeqt = "\\mmdatatypeqt"
        $mmdefaultsql = "\\mmdefaultsql"
        $mmdestemail = "\\mmdestemail"
        $mmdestfax = "\\mmdestfax"
        $mmdestnewdoc = "\\mmdestnewdoc"
        $mmdestprinter = "\\mmdestprinter"
        $mmerrors = "\\mmerrors"
        $mmfttypeaddress = "\\mmfttypeaddress"
        $mmfttypebarcode = "\\mmfttypebarcode"
        $mmfttypedbcolumn = "\\mmfttypedbcolumn"
        $mmfttypemapped = "\\mmfttypemapped"
        $mmfttypenull = "\\mmfttypenull"
        $mmfttypesalutation = "\\mmfttypesalutation"
        $mmheadersource = "\\mmheadersource"
        $mmjdsotype = "\\mmjdsotype"
        $mmlinktoquery = "\\mmlinktoquery"
        $mmmailsubject = "\\mmmailsubject"
        $mmmaintypecatalog = "\\mmmaintypecatalog"
        $mmmaintypeemail = "\\mmmaintypeemail"
        $mmmaintypeenvelopes = "\\mmmaintypeenvelopes"
        $mmmaintypefax = "\\mmmaintypefax"
        $mmmaintypelabels = "\\mmmaintypelabels"
        $mmmaintypeletters = "\\mmmaintypeletters"
        $mmodso = "\\mmodso"
        $mmodsoactive = "\\mmodsoactive"
        $mmodsocoldelim = "\\mmodsocoldelim"
        $mmodsocolumn = "\\mmodsocolumn"
        $mmodsodynaddr = "\\mmodsodynaddr"
        $mmodsofhdr = "\\mmodsofhdr"
        $mmodsofilter = "\\mmodsofilter"
        $mmodsofldmpdata = "\\mmodsofldmpdata"
        $mmodsofmcolumn = "\\mmodsofmcolumn"
        $mmodsohash = "\\mmodsohash"
        $mmodsolid = "\\mmodsolid"
        $mmodsomappedname = "\\mmodsomappedname"
        $mmodsoname = "\\mmodsoname"
        $mmodsorecipdata = "\\mmodsorecipdata"
        $mmodsosort = "\\mmodsosort"
        $mmodsosrc = "\\mmodsosrc"
        $mmodsotable = "\\mmodsotable"
        $mmodsoudl = "\\mmodsoudl"
        $mmodsoudldata = "\\mmodsoudldata"
        $mmodsouniquetag = "\\mmodsouniquetag"
        $mmquery = "\\mmquery"
        $mmreccur = "\\mmreccur"
        $mmshowdata = "\\mmshowdata"
   condition:
        any of them
}
rule rtf_math
{
    strings:
        $macc = "\\macc"
        $maccPr = "\\maccPr"
        $maln = "\\maln"
        $malnScr = "\\malnScr"
        $margPr = "\\margPr"
        $margSz = "\\margSz"
        $mbar = "\\mbar"
        $mbarPr = "\\mbarPr"
        $mbaseJc = "\\mbaseJc"
        $mbegChr = "\\mbegChr"
        $mborderBox = "\\mborderBox"
        $mborderBoxPr = "\\mborderBoxPr"
        $mbox = "\\mbox"
        $mboxPr = "\\mboxPr"
        $mbrk = "\\mbrk"
        $mbrkBin = "\\mbrkBin"
        $mbrkBinSub = "\\mbrkBinSub"
        $mcGp = "\\mcGp"
        $mcGpRule = "\\mcGpRule"
        $mchr = "\\mchr"
        $mcount = "\\mcount"
        $mcSp = "\\mcSp"
        $mctrlPr = "\\mctrlPr"
        $md = "\\md"
        $mdefJc = "\\mdefJc"
        $mdeg = "\\mdeg"
        $mdegHide = "\\mdegHide"
        $mden = "\\mden"
        $mdiff = "\\mdiff"
        $mdiffSty = "\\mdiffSty"
        $mdispdef = "\\mdispdef"
        $mdPr = "\\mdPr"
        $me = "\\me"
        $mendChr = "\\mendChr"
        $meqArr = "\\meqArr"
        $meqArrPr = "\\meqArrPr"
        $mf = "\\mf"
        $mfName = "\\mfName"
        $mfPr = "\\mfPr"
        $mfunc = "\\mfunc"
        $mfuncPr = "\\mfuncPr"
        $mgroupChr = "\\mgroupChr"
        $mgroupChrPr = "\\mgroupChrPr"
        $mgrow = "\\mgrow"
        $mhideBot = "\\mhideBot"
        $mhideLeft = "\\mhideLeft"
        $mhideRight = "\\mhideRight"
        $mhideTop = "\\mhideTop"
        $minterSp = "\\minterSp"
        $mintLim = "\\mintLim"
        $mintraSp = "\\mintraSp"
        $mjc = "\\mjc"
        $mlim = "\\mlim"
        $mlimloc = "\\mlimloc"
        $mlimlow = "\\mlimlow"
        $mlimlowPr = "\\mlimlowPr"
        $mlimupp = "\\mlimupp"
        $mlimuppPr = "\\mlimuppPr"
        $mlit = "\\mlit"
        $mlMargin = "\\mlMargin"
        $mm = "\\mm"
        $mmath = "\\mmath"
        $mmathFont = "\\mmathFont"
        $mmathPict = "\\mmathPict"
        $mmathPr = "\\mmathPr"
        $mmaxdist = "\\mmaxdist"
        $mmc = "\\mmc"
        $mmcJc = "\\mmcJc"
        $mmcPr = "\\mmcPr"
        $mmcs = "\\mmcs"
        $mmPr = "\\mmPr"
        $mmr = "\\mmr"
        $mnary = "\\mnary"
        $mnaryLim = "\\mnaryLim"
        $mnaryPr = "\\mnaryPr"
        $mnoBreak = "\\mnoBreak"
        $mnor = "\\mnor"
        $mnum = "\\mnum"
        $mobjDist = "\\mobjDist"
        $moMath = "\\moMath"
        $moMathPara = "\\moMathPara"
        $moMathParaPr = "\\moMathParaPr"
        $mopEmu = "\\mopEmu"
        $mphant = "\\mphant"
        $mphantPr = "\\mphantPr"
        $mplcHide = "\\mplcHide"
        $mpos = "\\mpos"
        $mpostSp = "\\mpostSp"
        $mpreSp = "\\mpreSp"
        $mr = "\\mr"
        $mrad = "\\mrad"
        $mradPr = "\\mradPr"
        $mrMargin = "\\mrMargin"
        $mrPr = "\\mrPr"
        $mrSp = "\\mrSp"
        $mrSpRule = "\\mrSpRule"
        $mscr = "\\mscr"
        $msepChr = "\\msepChr"
        $mshow = "\\mshow"
        $mshp = "\\mshp"
        $msmallFrac = "\\msmallFrac"
        $msPre = "\\msPre"
        $msPrePr = "\\msPrePr"
        $msSub = "\\msSub"
        $msSubPr = "\\msSubPr"
        $msSubSup = "\\msSubSup"
        $msSubSupPr = "\\msSubSupPr"
        $msSup = "\\msSup"
        $msSupPr = "\\msSupPr"
        $mstrikeBLTR = "\\mstrikeBLTR"
        $mstrikeH = "\\mstrikeH"
        $mstrikeTLBR = "\\mstrikeTLBR"
        $mstrikeV = "\\mstrikeV"
        $msty = "\\msty"
        $msub = "\\msub"
        $msubHide = "\\msubHide"
        $msup = "\\msup"
        $msupHide = "\\msupHide"
        $mtransp = "\\mtransp"
        $mtype = "\\mtype"
        $mvertJc = "\\mvertJc"
        $mwrapIndent = "\\mwrapIndent"
        $mwrapRight = "\\mwrapRight"
        $mzeroAsc = "\\mzeroAsc"
        $mzeroDesc = "\\mzeroDesc"
        $mzeroWid = "\\mzeroWid"
   condition:
        any of them
}
rule rtf_outlook
{
    strings:
        $ebcstart = "\\ebcstart"
        $ebcend = "\\ebcend"
   condition:
        any of them
}
rule rtf_objects
{
    strings:
        $linkself = "\\linkself"
        $objalias = "\\objalias"
        $objalign = "\\objalign"
        $objattph = "\\objattph"
        $objautlink = "\\objautlink"
        $objclass = "\\objclass"
        $objcropb = "\\objcropb"
        $objcropl = "\\objcropl"
        $objcropr = "\\objcropr"
        $objcropt = "\\objcropt"
        $objdata = "\\objdata"
        $object = "\\object"
        $objemb = "\\objemb"
        $objh = "\\objh"
        $objhtml = "\\objhtml"
        $objicemb = "\\objicemb"
        $objlink = "\\objlink"
        $objlock = "\\objlock"
        $objname = "\\objname"
        $objocx = "\\objocx"
        $objpub = "\\objpub"
        $objscalex = "\\objscalex"
        $objscaley = "\\objscaley"
        $objsect = "\\objsect"
        $objsetsize = "\\objsetsize"
        $objsub = "\\objsub"
        $objtime = "\\objtime"
        $objtransy = "\\objtransy"
        $objupdate = "\\objupdate"
        $objw = "\\objw"
        $oleclsid = "\\oleclsid"
        $result = "\\result"
        $rsltbmp = "\\rsltbmp"
        $rslthtml = "\\rslthtml"
        $rsltmerge = "\\rsltmerge"
        $rsltpict = "\\rsltpict"
        $rsltrtf = "\\rsltrtf"
        $rslttxt = "\\rslttxt"
   condition:
        any of them
}
rule rtf_paragraph
{
    strings:
        $box = "\\box"
        $brdrb = "\\brdrb"
        $brdrbar = "\\brdrbar"
        $brdrbtw = "\\brdrbtw"
        $brdrcf = "\\brdrcf"
        $brdrdash = "\\brdrdash"
        $brdrdashd = "\\brdrdashd"
        $brdrdashdd = "\\brdrdashdd"
        $brdrdashdot = "\\brdrdashdot"
        $brdrdashdotdot = "\\brdrdashdotdot"
        $brdrdashdotstr = "\\brdrdashdotstr"
        $brdrdashsm = "\\brdrdashsm"
        $brdrdb = "\\brdrdb"
        $brdrdot = "\\brdrdot"
        $brdremboss = "\\brdremboss"
        $brdrengrave = "\\brdrengrave"
        $brdrframe = "\\brdrframe"
        $brdrhair = "\\brdrhair"
        $brdrinset = "\\brdrinset"
        $brdrl = "\\brdrl"
        $brdrnil = "\\brdrnil"
        $brdrnone = "\\brdrnone"
        $brdroutset = "\\brdroutset"
        $brdrr = "\\brdrr"
        $brdrs = "\\brdrs"
        $brdrsh = "\\brdrsh"
        $brdrt = "\\brdrt"
        $brdrtbl = "\\brdrtbl"
        $brdrth = "\\brdrth"
        $brdrthtnlg = "\\brdrthtnlg"
        $brdrthtnmg = "\\brdrthtnmg"
        $brdrthtnsg = "\\brdrthtnsg"
        $brdrtnthlg = "\\brdrtnthlg"
        $brdrtnthmg = "\\brdrtnthmg"
        $brdrtnthsg = "\\brdrtnthsg"
        $brdrtnthtnlg = "\\brdrtnthtnlg"
        $brdrtnthtnmg = "\\brdrtnthtnmg"
        $brdrtnthtnsg = "\\brdrtnthtnsg"
        $brdrtriple = "\\brdrtriple"
        $brdrw = "\\brdrw"
        $brdrwavy = "\\brdrwavy"
        $brdrwavydb = "\\brdrwavydb"
        $brsp = "\\brsp"
        $aspalpha = "\\aspalpha"
        $aspnum = "\\aspnum"
        $collapsed = "\\collapsed"
        $contextualspace = "\\contextualspace"
        $cufi = "\\cufi"
        $culi = "\\culi"
        $curi = "\\curi"
        $faauto = "\\faauto"
        $facenter = "\\facenter"
        $fafixed = "\\fafixed"
        $fahang = "\\fahang"
        $faroman = "\\faroman"
        $favar = "\\favar"
        $fi = "\\fi"
        $hyphpar = "\\hyphpar"
        $indmirror = "\\indmirror"
        $intbl = "\\intbl"
        $itap = "\\itap"
        $keep = "\\keep"
        $keepn = "\\keepn"
        $level = "\\level"
        $li = "\\li"
        $lin = "\\lin"
        $lisa = "\\lisa"
        $lisb = "\\lisb"
        $ltrpar = "\\ltrpar"
        $nocwrap = "\\nocwrap"
        $noline = "\\noline"
        $nooverflow = "\\nooverflow"
        $nosnaplinegrid = "\\nosnaplinegrid"
        $nowidctlpar = "\\nowidctlpar"
        $nowwrap = "\\nowwrap"
        $outlinelevel = "\\outlinelevel"
        $pagebb = "\\pagebb"
        $pard = "\\pard"
        $prauth = "\\prauth"
        $prdate = "\\prdate"
        $qc = "\\qc"
        $qd = "\\qd"
        $qj = "\\qj"
        $qk = "\\qk"
        $ql = "\\ql"
        $qr = "\\qr"
        $qt = "\\qt"
        $ri = "\\ri"
        $rin = "\\rin"
        $rtlpar = "\\rtlpar"
        $s = "\\s"
        $sa = "\\sa"
        $saauto = "\\saauto"
        $sb = "\\sb"
        $sbauto = "\\sbauto"
        $sbys = "\\sbys"
        $sl = "\\sl"
        $slmult = "\\slmult"
        $spv = "\\spv"
        $subdocument = "\\subdocument"
        $tscbandhorzeven = "\\tscbandhorzeven"
        $tscbandhorzodd = "\\tscbandhorzodd"
        $tscbandverteven = "\\tscbandverteven"
        $tscbandvertodd = "\\tscbandvertodd"
        $tscfirstcol = "\\tscfirstcol"
        $tscfirstrow = "\\tscfirstrow"
        $tsclastcol = "\\tsclastcol"
        $tsclastrow = "\\tsclastrow"
        $tscnecell = "\\tscnecell"
        $tscnwcell = "\\tscnwcell"
        $tscsecell = "\\tscsecell"
        $tscswcell = "\\tscswcell"
        $txbxtwalways = "\\txbxtwalways"
        $txbxtwfirst = "\\txbxtwfirst"
        $txbxtwfirstlast = "\\txbxtwfirstlast"
        $txbxtwlast = "\\txbxtwlast"
        $txbxtwno = "\\txbxtwno"
        $widctlpar = "\\widctlpar"
        $yts = "\\yts"
        $pgp = "\\pgp"
        $pgptbl = "\\pgptbl"
        $ipgp = "\\ipgp"
        $dfrauth = "\\dfrauth"
        $dfrdate = "\\dfrdate"
        $dfrstart = "\\dfrstart"
        $dfrstop = "\\dfrstop"
        $dfrxst = "\\dfrxst"
        $bgbdiag = "\\bgbdiag"
        $bgcross = "\\bgcross"
        $bgdcross = "\\bgdcross"
        $bgdkbdiag = "\\bgdkbdiag"
        $bgdkcross = "\\bgdkcross"
        $bgdkdcross = "\\bgdkdcross"
        $bgdkfdiag = "\\bgdkfdiag"
        $bgdkhoriz = "\\bgdkhoriz"
        $bgdkvert = "\\bgdkvert"
        $bgfdiag = "\\bgfdiag"
        $bghoriz = "\\bghoriz"
        $bgvert = "\\bgvert"
        $cbpat = "\\cbpat"
        $cfpat = "\\cfpat"
        $shading = "\\shading"
   condition:
        any of them
}

rule rtf_pictures
{
    strings:
        $bin = "\\bin"
        $bliptag = "\\bliptag"
        $blipuid = "\\blipuid"
        $blipupi = "\\blipupi"
        $defshp = "\\defshp"
        $dibitmap = "\\dibitmap"
        $emfblip = "\\emfblip"
        $jpegblip = "\\jpegblip"
        $macpict = "\\macpict"
        $nonshppict = "\\nonshppict"
        $picbmp = "\\picbmp"
        $picbpp = "\\picbpp"
        $piccropb = "\\piccropb"
        $piccropl = "\\piccropl"
        $piccropr = "\\piccropr"
        $piccropt = "\\piccropt"
        $pich = "\\pich"
        $pichgoal = "\\pichgoal"
        $picprop = "\\picprop"
        $picscaled = "\\picscaled"
        $picscalex = "\\picscalex"
        $picscaley = "\\picscaley"
        $pict = "\\pict"
        $picw = "\\picw"
        $picwgoal = "\\picwgoal"
        $pmmetafile = "\\pmmetafile"
        $pngblip = "\\pngblip"
        $shppict = "\\shppict"
        $wbitmap = "\\wbitmap"
        $wbmbitspixel = "\\wbmbitspixel"
        $wbmplanes = "\\wbmplanes"
        $wbmwidthbyte = "\\wbmwidthbyte"
        $wmetafile = "\\wmetafile"
   condition:
        any of them
}
rule rtf_position
{
    strings:
        $absh = "\\absh"
        $abslock = "\\abslock"
        $absnoovrlp = "\\absnoovrlp"
        $absw = "\\absw"
        $dfrmtxtx = "\\dfrmtxtx"
        $dfrmtxty = "\\dfrmtxty"
        $dropcapli = "\\dropcapli"
        $dropcapt = "\\dropcapt"
        $dxfrtext = "\\dxfrtext"
        $frmtxbtlr = "\\frmtxbtlr"
        $frmtxlrtb = "\\frmtxlrtb"
        $frmtxlrtbv = "\\frmtxlrtbv"
        $frmtxtbrl = "\\frmtxtbrl"
        $frmtxtbrlv = "\\frmtxtbrlv"
        $nowrap = "\\nowrap"
        $overlay = "\\overlay"
        $phcol = "\\phcol"
        $phmrg = "\\phmrg"
        $phpg = "\\phpg"
        $posnegx = "\\posnegx"
        $posnegy = "\\posnegy"
        $posx = "\\posx"
        $posxc = "\\posxc"
        $posxi = "\\posxi"
        $posxl = "\\posxl"
        $posxo = "\\posxo"
        $posxr = "\\posxr"
        $posy = "\\posy"
        $posyb = "\\posyb"
        $posyc = "\\posyc"
        $posyil = "\\posyil"
        $posyin = "\\posyin"
        $posyout = "\\posyout"
        $posyt = "\\posyt"
        $pvmrg = "\\pvmrg"
        $pvpara = "\\pvpara"
        $pvpg = "\\pvpg"
        $wraparound = "\\wraparound"
        $wrapdefault = "\\wrapdefault"
        $wrapthrough = "\\wrapthrough"
        $wraptight = "\\wraptight"
    condition:
        any of them
}
rule rtf_protection
{
    strings:
        $protend = "\\protend"
        $protstart = "\\protstart"
        $protusertbl = "\\protusertbl"
   condition:
        any of them
}
rule rtf_quick_styles
{
    strings:
        $noqfpromote = "\\noqfpromote"
   condition:
        any of them
}
rule rtf_password
{
    strings:
        $password = "\\password"
        $passwordhash = "\\passwordhash"
   condition:
        any of them
}
rule rtf_revision
{
    strings:
        $pnrauth = "\\pnrauth"
        $pnrdate = "\\pnrdate"
        $pnrnfc = "\\pnrnfc"
        $pnrnot = "\\pnrnot"
        $pnrpnbr = "\\pnrpnbr"
        $pnrrgb = "\\pnrrgb"
        $pnrstart = "\\pnrstart"
        $pnrstop = "\\pnrstop"
        $pnrxst = "\\pnrxst"
   condition:
        any of them
}
rule rtf_version
{
    strings:
        $rtf = "\\rtf"
   condition:
        any of them
}
rule rtf_section
{
    strings:
        $adjustright = "\\adjustright"
        $binfsxn = "\\binfsxn"
        $binsxn = "\\binsxn"
        $colno = "\\colno"
        $cols = "\\cols"
        $colsr = "\\colsr"
        $colsx = "\\colsx"
        $colw = "\\colw"
        $ds = "\\ds"
        $endnhere = "\\endnhere"
        $footery = "\\footery"
        $guttersxn = "\\guttersxn"
        $headery = "\\headery"
        $horzsect = "\\horzsect"
        $linebetcol = "\\linebetcol"
        $linecont = "\\linecont"
        $linemod = "\\linemod"
        $lineppage = "\\lineppage"
        $linerestart = "\\linerestart"
        $linestarts = "\\linestarts"
        $linex = "\\linex"
        $lndscpsxn = "\\lndscpsxn"
        $ltrsect = "\\ltrsect"
        $margbsxn = "\\margbsxn"
        $marglsxn = "\\marglsxn"
        $margmirsxn = "\\margmirsxn"
        $margrsxn = "\\margrsxn"
        $margtsxn = "\\margtsxn"
        $pghsxn = "\\pghsxn"
        $pgnbidia = "\\pgnbidia"
        $pgnbidib = "\\pgnbidib"
        $pgnchosung = "\\pgnchosung"
        $pgncnum = "\\pgncnum"
        $pgncont = "\\pgncont"
        $pgndbnum = "\\pgndbnum"
        $pgndbnumd = "\\pgndbnumd"
        $pgndbnumk = "\\pgndbnumk"
        $pgndbnumt = "\\pgndbnumt"
        $pgndec = "\\pgndec"
        $pgndecd = "\\pgndecd"
        $pgnganada = "\\pgnganada"
        $pgngbnum = "\\pgngbnum"
        $pgngbnumd = "\\pgngbnumd"
        $pgngbnumk = "\\pgngbnumk"
        $pgngbnuml = "\\pgngbnuml"
        $pgnhindia = "\\pgnhindia"
        $pgnhindib = "\\pgnhindib"
        $pgnhindic = "\\pgnhindic"
        $pgnhindid = "\\pgnhindid"
        $pgnhn = "\\pgnhn"
        $pgnhnsc = "\\pgnhnsc"
        $pgnhnsh = "\\pgnhnsh"
        $pgnhnsm = "\\pgnhnsm"
        $pgnhnsn = "\\pgnhnsn"
        $pgnhnsp = "\\pgnhnsp"
        $pgnid = "\\pgnid"
        $pgnlcltr = "\\pgnlcltr"
        $pgnlcrm = "\\pgnlcrm"
        $pgnrestart = "\\pgnrestart"
        $pgnstarts = "\\pgnstarts"
        $pgnthaia = "\\pgnthaia"
        $pgnthaib = "\\pgnthaib"
        $pgnthaic = "\\pgnthaic"
        $pgnucltr = "\\pgnucltr"
        $pgnucrm = "\\pgnucrm"
        $pgnvieta = "\\pgnvieta"
        $pgnx = "\\pgnx"
        $pgny = "\\pgny"
        $pgnzodiac = "\\pgnzodiac"
        $pgnzodiacd = "\\pgnzodiacd"
        $pgnzodiacl = "\\pgnzodiacl"
        $pgwsxn = "\\pgwsxn"
        $pnseclvl = "\\pnseclvl"
        $rtlsect = "\\rtlsect"
        $saftnnalc = "\\saftnnalc"
        $saftnnar = "\\saftnnar"
        $saftnnauc = "\\saftnnauc"
        $saftnnchi = "\\saftnnchi"
        $saftnnchosung = "\\saftnnchosung"
        $saftnncnum = "\\saftnncnum"
        $saftnndbar = "\\saftnndbar"
        $saftnndbnum = "\\saftnndbnum"
        $saftnndbnumd = "\\saftnndbnumd"
        $saftnndbnumk = "\\saftnndbnumk"
        $saftnndbnumt = "\\saftnndbnumt"
        $saftnnganada = "\\saftnnganada"
        $saftnngbnum = "\\saftnngbnum"
        $saftnngbnumd = "\\saftnngbnumd"
        $saftnngbnumk = "\\saftnngbnumk"
        $saftnngbnuml = "\\saftnngbnuml"
        $saftnnrlc = "\\saftnnrlc"
        $saftnnruc = "\\saftnnruc"
        $saftnnzodiac = "\\saftnnzodiac"
        $saftnnzodiacd = "\\saftnnzodiacd"
        $saftnnzodiacl = "\\saftnnzodiacl"
        $saftnrestart = "\\saftnrestart"
        $saftnrstcont = "\\saftnrstcont"
        $saftnstart = "\\saftnstart"
        $sbkcol = "\\sbkcol"
        $sbkeven = "\\sbkeven"
        $sbknone = "\\sbknone"
        $sbkodd = "\\sbkodd"
        $sbkpage = "\\sbkpage"
        $sectd = "\\sectd"
        $sectdefaultcl = "\\sectdefaultcl"
        $sectexpand = "\\sectexpand"
        $sectlinegrid = "\\sectlinegrid"
        $sectspecifycl = "\\sectspecifycl"
        $sectspecifygen = "\\sectspecifygen"
        $sectspecifyl = "\\sectspecifyl"
        $sectunlocked = "\\sectunlocked"
        $sftnbj = "\\sftnbj"
        $sftnnalc = "\\sftnnalc"
        $sftnnar = "\\sftnnar"
        $sftnnauc = "\\sftnnauc"
        $sftnnchi = "\\sftnnchi"
        $sftnnchosung = "\\sftnnchosung"
        $sftnncnum = "\\sftnncnum"
        $sftnndbar = "\\sftnndbar"
        $sftnndbnum = "\\sftnndbnum"
        $sftnndbnumd = "\\sftnndbnumd"
        $sftnndbnumk = "\\sftnndbnumk"
        $sftnndbnumt = "\\sftnndbnumt"
        $sftnnganada = "\\sftnnganada"
        $sftnngbnum = "\\sftnngbnum"
        $sftnngbnumd = "\\sftnngbnumd"
        $sftnngbnumk = "\\sftnngbnumk"
        $sftnngbnuml = "\\sftnngbnuml"
        $sftnnrlc = "\\sftnnrlc"
        $sftnnruc = "\\sftnnruc"
        $sftnnzodiac = "\\sftnnzodiac"
        $sftnnzodiacd = "\\sftnnzodiacd"
        $sftnnzodiacl = "\\sftnnzodiacl"
        $sftnrestart = "\\sftnrestart"
        $sftnrstcont = "\\sftnrstcont"
        $sftnrstpg = "\\sftnrstpg"
        $sftnstart = "\\sftnstart"
        $sftntj = "\\sftntj"
        $srauth = "\\srauth"
        $srdate = "\\srdate"
        $titlepg = "\\titlepg"
        $vertal = "\\vertal"
        $vertalb = "\\vertalb"
        $vertalc = "\\vertalc"
        $vertalj = "\\vertalj"
        $vertalt = "\\vertalt"
        $vertsect = "\\vertsect"
        $stextflow = "\\stextflow"
   condition:
        any of them
}
rule rtf_tag
{
    strings:
        $factoidname = "\\factoidname"
    condition:
        any of them
}

rule rtf_special_hex
{
    strings:
        $hex = "\\'"
    condition:
        any of them
}

rule rtf_special_ignore
{
    strings:
        $ignore = "\\*"
    condition:
        any of them
}


rule rtf_special
{
    strings:
        $hyphen = "\\-"
        $subentry = "\\:"
        $nonbreakhyphen = "\\_"
        $formula = "\\|"
        $nonbreakspace = "\\~"
/*
        ${ = "\\{"
        $} = "\\}"
*/
        $bullet = "\\bullet"
        $chatn = "\\chatn"
        $chdate = "\\chdate"
        $chdpa = "\\chdpa"
        $chdpl = "\\chdpl"
        $chftn = "\\chftn"
        $chftnsep = "\\chftnsep"
        $chftnsepc = "\\chftnsepc"
        $chpgn = "\\chpgn"
        $chtime = "\\chtime"
        $column = "\\column"
        $emdash = "\\emdash"
        $emspace = "\\emspace"
        $endash = "\\endash"
        $enspace = "\\enspace"
        $lbr = "\\lbr"
        $ldblquote = "\\ldblquote"
        $line = "\\line"
        $lquote = "\\lquote"
        $ltrmark = "\\ltrmark"
        $page = "\\page"
        $par = "\\par"
        $qmspace = "\\qmspace"
        $rdblquote = "\\rdblquote"
        $row = "\\row"
        $rquote = "\\rquote"
        $rtlmark = "\\rtlmark"
        $sect = "\\sect"
        $sectnum = "\\sectnum"
        $softcol = "\\softcol"
        $softlheight = "\\softlheight"
        $softline = "\\softline"
        $softpage = "\\softpage"
        $tab = "\\tab"
        $zwbo = "\\zwbo"
        $zwj = "\\zwj"
        $zwnbo = "\\zwnbo"
        $zwnj = "\\zwnj"
   condition:
        any of them
    }

rule rtf_styles
{
    strings:
        $latentstyles = "\\latentstyles"
        $lsdlocked = "\\lsdlocked"
        $lsdlockeddef = "\\lsdlockeddef"
        $lsdlockedexcept = "\\lsdlockedexcept"
        $lsdpriority = "\\lsdpriority"
        $lsdprioritydef = "\\lsdprioritydef"
        $lsdqformat = "\\lsdqformat"
        $lsdqformatdef = "\\lsdqformatdef"
        $lsdsemihidden = "\\lsdsemihidden"
        $lsdsemihiddendef = "\\lsdsemihiddendef"
        $lsdstimax = "\\lsdstimax"
        $lsdunhideused = "\\lsdunhideused"
        $lsdunhideuseddef = "\\lsdunhideuseddef"
        $additive = "\\additive"
        $alt = "\\alt"
        $ctrl = "\\ctrl"
        $fn = "\\fn"
        $keycode = "\\keycode"
        $sautoupd = "\\sautoupd"
        $sbasedon = "\\sbasedon"
        $scompose = "\\scompose"
        $shidden = "\\shidden"
        $shift = "\\shift"
        $slink = "\\slink"
        $slocked = "\\slocked"
        $snext = "\\snext"
        $spersonal = "\\spersonal"
        $spriority = "\\spriority"
        $sqformat = "\\sqformat"
        $sreply = "\\sreply"
        $ssemihidden = "\\ssemihidden"
        $stylesheet = "\\stylesheet"
        $styrsid = "\\styrsid"
        $sunhideused = "\\sunhideused"
        $ts = "\\ts"
        $tsrowd = "\\tsrowd"
   condition:
        any of them
}
rule rtf_tables
{
    strings:
        $cell = "\\cell"
        $cellx = "\\cellx"
        $clbgbdiag = "\\clbgbdiag"
        $clbgcross = "\\clbgcross"
        $clbgdcross = "\\clbgdcross"
        $clbgdkbdiag = "\\clbgdkbdiag"
        $clbgdkcross = "\\clbgdkcross"
        $clbgdkdcross = "\\clbgdkdcross"
        $clbgdkfdiag = "\\clbgdkfdiag"
        $clbgdkhor = "\\clbgdkhor"
        $clbgdkvert = "\\clbgdkvert"
        $clbgfdiag = "\\clbgfdiag"
        $clbghoriz = "\\clbghoriz"
        $clbgvert = "\\clbgvert"
        $clbrdrb = "\\clbrdrb"
        $clbrdrl = "\\clbrdrl"
        $clbrdrr = "\\clbrdrr"
        $clbrdrt = "\\clbrdrt"
        $clcbpat = "\\clcbpat"
        $clcbpatraw = "\\clcbpatraw"
        $clcfpat = "\\clcfpat"
        $clcfpatraw = "\\clcfpatraw"
        $cldel2007 = "\\cldel2007"
        $cldelauth = "\\cldelauth"
        $cldeldttm = "\\cldeldttm"
        $cldgll = "\\cldgll"
        $cldglu = "\\cldglu"
        $clFitText = "\\clFitText"
        $clftsWidth = "\\clftsWidth"
        $clhidemark2007 = "\\clhidemark2007"
        $clins2007 = "\\clins2007"
        $clinsauth = "\\clinsauth"
        $clinsdttm = "\\clinsdttm"
        $clmgf = "\\clmgf"
        $clmrg = "\\clmrg"
        $clmrgd = "\\clmrgd"
        $clmrgdauth = "\\clmrgdauth"
        $clmrgddttm = "\\clmrgddttm"
        $clmrgdr = "\\clmrgdr"
        $clNoWrap = "\\clNoWrap"
        $clpadb = "\\clpadb"
        $clpadfb = "\\clpadfb"
        $clpadfl = "\\clpadfl"
        $clpadfr = "\\clpadfr"
        $clpadft = "\\clpadft"
        $clpadl = "\\clpadl"
        $clpadr = "\\clpadr"
        $clpadt = "\\clpadt"
        $clspb = "\\clspb"
        $clspfb = "\\clspfb"
        $clspfl = "\\clspfl"
        $clspfr = "\\clspfr"
        $clspft = "\\clspft"
        $clspl = "\\clspl"
        $clspr = "\\clspr"
        $clspt = "\\clspt"
        $clshdng = "\\clshdng"
        $clshdngraw = "\\clshdngraw"
        $clshdrawnil = "\\clshdrawnil"
        $clsplit = "\\clsplit"
        $clsplitr = "\\clsplitr"
        $cltxbtlr = "\\cltxbtlr"
        $cltxlrtb = "\\cltxlrtb"
        $cltxlrtbv = "\\cltxlrtbv"
        $cltxtbrl = "\\cltxtbrl"
        $cltxtbrlv = "\\cltxtbrlv"
        $clvertalb = "\\clvertalb"
        $clvertalc = "\\clvertalc"
        $clvertalt = "\\clvertalt"
        $clvmgf = "\\clvmgf"
        $clvmrg = "\\clvmrg"
        $clwWidth = "\\clwWidth"
        $irowband = "\\irowband"
        $irow = "\\irow"
        $lastrow = "\\lastrow"
        $ltrrow = "\\ltrrow"
        $nestcell = "\\nestcell"
        $nestrow = "\\nestrow"
        $nesttableprops = "\\nesttableprops"
        $nonesttables = "\\nonesttables"
        $rawclbgdkbdiag = "\\rawclbgdkbdiag"
        $rawclbgbdiag = "\\rawclbgbdiag"
        $rawclbgcross = "\\rawclbgcross"
        $rawclbgdcross = "\\rawclbgdcross"
        $rawclbgdkcross = "\\rawclbgdkcross"
        $rawclbgdkdcross = "\\rawclbgdkdcross"
        $rawclbgdkfdiag = "\\rawclbgdkfdiag"
        $rawclbgdkhor = "\\rawclbgdkhor"
        $rawclbgdkvert = "\\rawclbgdkvert"
        $rawclbgfdiag = "\\rawclbgfdiag"
        $rawclbghoriz = "\\rawclbghoriz"
        $rawclbgvert = "\\rawclbgvert"
        $rtlrow = "\\rtlrow"
        $tabsnoovrlp = "\\tabsnoovrlp"
        $taprtl = "\\taprtl"
        $tblind = "\\tblind"
        $tblindtype = "\\tblindtype"
        $tbllkbestfit = "\\tbllkbestfit"
        $tbllkborder = "\\tbllkborder"
        $tbllkcolor = "\\tbllkcolor"
        $tbllkfont = "\\tbllkfont"
        $tbllkhdrcols = "\\tbllkhdrcols"
        $tbllkhdrrows = "\\tbllkhdrrows"
        $tbllklastcol = "\\tbllklastcol"
        $tbllklastrow = "\\tbllklastrow"
        $tbllknocolband = "\\tbllknocolband"
        $tbllknorowband = "\\tbllknorowband"
        $tbllkshading = "\\tbllkshading"
        $tcelld = "\\tcelld"
        $tdfrmtxtBottom = "\\tdfrmtxtBottom"
        $tdfrmtxtLeft = "\\tdfrmtxtLeft"
        $tdfrmtxtRight = "\\tdfrmtxtRight"
        $tdfrmtxtTop = "\\tdfrmtxtTop"
        $tphcol = "\\tphcol"
        $tphmrg = "\\tphmrg"
        $tphpg = "\\tphpg"
        $tposnegx = "\\tposnegx"
        $tposnegy = "\\tposnegy"
        $tposxc = "\\tposxc"
        $tposxi = "\\tposxi"
        $tposxl = "\\tposxl"
        $tposx = "\\tposx"
        $tposxo = "\\tposxo"
        $tposxr = "\\tposxr"
        $tposy = "\\tposy"
        $tposyb = "\\tposyb"
        $tposyc = "\\tposyc"
        $tposyil = "\\tposyil"
        $tposyin = "\\tposyin"
        $tposyout = "\\tposyout"
        $tposyt = "\\tposyt"
        $tpvmrg = "\\tpvmrg"
        $tpvpara = "\\tpvpara"
        $tpvpg = "\\tpvpg"
        $trauth = "\\trauth"
        $trautofit = "\\trautofit"
        $trbgbdiag = "\\trbgbdiag"
        $trbgcross = "\\trbgcross"
        $trbgdcross = "\\trbgdcross"
        $trbgdkbdiag = "\\trbgdkbdiag"
        $trbgdkcross = "\\trbgdkcross"
        $trbgdkdcross = "\\trbgdkdcross"
        $trbgdkfdiag = "\\trbgdkfdiag"
        $trbgdkhor = "\\trbgdkhor"
        $trbgdkvert = "\\trbgdkvert"
        $trbgfdiag = "\\trbgfdiag"
        $trbghoriz = "\\trbghoriz"
        $trbgvert = "\\trbgvert"
        $trbrdrb = "\\trbrdrb"
        $trbrdrh = "\\trbrdrh"
        $trbrdrl = "\\trbrdrl"
        $trbrdrr = "\\trbrdrr"
        $trbrdrt = "\\trbrdrt"
        $trbrdrv = "\\trbrdrv"
        $trcbpat = "\\trcbpat"
        $trcfpat = "\\trcfpat"
        $trdate = "\\trdate"
        $trftsWidthA = "\\trftsWidthA"
        $trftsWidthB = "\\trftsWidthB"
        $trftsWidth = "\\trftsWidth"
        $trgaph = "\\trgaph"
        $trhdr = "\\trhdr"
        $trkeep = "\\trkeep"
        $trkeepfollow = "\\trkeepfollow"
        $trleft = "\\trleft"
        $trowd = "\\trowd"
        $trpaddb = "\\trpaddb"
        $trpaddfb = "\\trpaddfb"
        $trpaddfl = "\\trpaddfl"
        $trpaddfr = "\\trpaddfr"
        $trpaddft = "\\trpaddft"
        $trpaddl = "\\trpaddl"
        $trpaddr = "\\trpaddr"
        $trpaddt = "\\trpaddt"
        $trpadob = "\\trpadob"
        $trpadofb = "\\trpadofb"
        $trpadofl = "\\trpadofl"
        $trpadofr = "\\trpadofr"
        $trpadoft = "\\trpadoft"
        $trpadol = "\\trpadol"
        $trpador = "\\trpador"
        $trpadot = "\\trpadot"
        $trpat = "\\trpat"
        $trqc = "\\trqc"
        $trql = "\\trql"
        $trqr = "\\trqr"
        $trrh = "\\trrh"
        $trshdng = "\\trshdng"
        $trspdb = "\\trspdb"
        $trspdfb = "\\trspdfb"
        $trspdfl = "\\trspdfl"
        $trspdfr = "\\trspdfr"
        $trspdft = "\\trspdft"
        $trspdl = "\\trspdl"
        $trspdr = "\\trspdr"
        $trspdt = "\\trspdt"
        $trspob = "\\trspob"
        $trspofb = "\\trspofb"
        $trspofl = "\\trspofl"
        $trspofr = "\\trspofr"
        $trspoft = "\\trspoft"
        $trspol = "\\trspol"
        $trspor = "\\trspor"
        $trspot = "\\trspot"
        $trwWidthA = "\\trwWidthA"
        $trwWidthB = "\\trwWidthB"
        $trwWidth = "\\trwWidth"
        $tc = "\\tc"
        $tcf = "\\tcf"
        $tcl = "\\tcl"
        $tcn = "\\tcn"
        $tsbgbdiag = "\\tsbgbdiag"
        $tsbgcross = "\\tsbgcross"
        $tsbgdcross = "\\tsbgdcross"
        $tsbgdkbdiag = "\\tsbgdkbdiag"
        $tsbgdkcross = "\\tsbgdkcross"
        $tsbgdkdcross = "\\tsbgdkdcross"
        $tsbgdkfdiag = "\\tsbgdkfdiag"
        $tsbgdkhor = "\\tsbgdkhor"
        $tsbgdkvert = "\\tsbgdkvert"
        $tsbgfdiag = "\\tsbgfdiag"
        $tsbghoriz = "\\tsbghoriz"
        $tsbgvert = "\\tsbgvert"
        $tsbrdrb = "\\tsbrdrb"
        $tsbrdrdgl = "\\tsbrdrdgl"
        $tsbrdrdgr = "\\tsbrdrdgr"
        $tsbrdrh = "\\tsbrdrh"
        $tsbrdrl = "\\tsbrdrl"
        $tsbrdrr = "\\tsbrdrr"
        $tsbrdrt = "\\tsbrdrt"
        $tsbrdrv = "\\tsbrdrv"
        $tscbandsh = "\\tscbandsh"
        $tscbandsv = "\\tscbandsv"
        $tscellcbpat = "\\tscellcbpat"
        $tscellcfpat = "\\tscellcfpat"
        $tscellpaddb = "\\tscellpaddb"
        $tscellpaddfb = "\\tscellpaddfb"
        $tscellpaddfl = "\\tscellpaddfl"
        $tscellpaddfr = "\\tscellpaddfr"
        $tscellpaddft = "\\tscellpaddft"
        $tscellpaddl = "\\tscellpaddl"
        $tscellpaddr = "\\tscellpaddr"
        $tscellpaddt = "\\tscellpaddt"
        $tscellpct = "\\tscellpct"
        $tscellwidth = "\\tscellwidth"
        $tscellwidthfts = "\\tscellwidthfts"
        $tsnowrap = "\\tsnowrap"
        $tsvertalb = "\\tsvertalb"
        $tsvertalc = "\\tsvertalc"
        $tsvertalt = "\\tsvertalt"
        $tb = "\\tb"
        $tldot = "\\tldot"
        $tleq = "\\tleq"
        $tlhyph = "\\tlhyph"
        $tlmdot = "\\tlmdot"
        $tlth = "\\tlth"
        $tlul = "\\tlul"
        $tqc = "\\tqc"
        $tqdec = "\\tqdec"
        $tqr = "\\tqr"
        $tx = "\\tx"
    condition:
        any of them
}
rule rtf_theme
{
    strings:
        $themedata = "\\themedata"
        $fbimajor = "\\fbimajor"
        $fbiminor = "\\fbiminor"
        $fdbmajor = "\\fdbmajor"
        $fdbminor = "\\fdbminor"
        $fhimajor = "\\fhimajor"
        $fhiminor = "\\fhiminor"
        $flomajor = "\\flomajor"
        $flominor = "\\flominor"
        $revtbl = "\\revtbl"
        $charrsid = "\\charrsid"
        $delrsid = "\\delrsid"
        $insrsid = "\\insrsid"
        $oldcprops = "\\oldcprops"
        $oldpprops = "\\oldpprops"
        $oldsprops = "\\oldsprops"
        $oldtprops = "\\oldtprops"
        $pararsid = "\\pararsid"
        $rsid = "\\rsid"
        $rsidroot = "\\rsidroot"
        $rsidtbl = "\\rsidtbl"
        $sectrsid = "\\sectrsid"
        $tblrsid = "\\tblrsid"
   condition:
        any of them
}
rule rtf_unicode
{
    strings:
        $u = "\\u"
        $uc = "\\uc"
        $ud = "\\ud"
        $upr = "\\upr"
   condition:
        any of them
}

rule rtf_shapes
{
    strings:
        $shp = "\\shp"
        $shpbottom = "\\shpbottom"
        $shpbxcolumn = "\\shpbxcolumn"
        $shpbxignore = "\\shpbxignore"
        $shpbxmargin = "\\shpbxmargin"
        $shpbxpage = "\\shpbxpage"
        $shpbyignore = "\\shpbyignore"
        $shpbymargin = "\\shpbymargin"
        $shpbypage = "\\shpbypage"
        $shpbypara = "\\shpbypara"
        $shpfblwtxt = "\\shpfblwtxt"
        $shpfhdr = "\\shpfhdr"
        $shpgrp = "\\shpgrp"
        $shpinst = "\\shpinst"
        $shpleft = "\\shpleft"
        $shplid = "\\shplid"
        $shplockanchor = "\\shplockanchor"
        $shpright = "\\shpright"
        $shprslt = "\\shprslt"
        $shptop = "\\shptop"
        $shptxt = "\\shptxt"
        $shpwrk = "\\shpwrk"
        $shpwr = "\\shpwr"
        $shpz = "\\shpz"
        $sn = "\\sn"
        $sp = "\\sp"
        $sv = "\\sv"
        $svb = "\\svb"
    condition:
        any of them
}


"""        
        
